language: ruby

services: 
  - docker

before_install:
 # Setup your application stack. You may need to tweak these commands if you
 # doing out-of-the-ordinary docker-compose builds.
 #- docker-compose pull
 - docker-compose build
 - docker-compose up -d
 - sleep 30
 - docker-compose ps
 - cd app && bundle install 

script:
 - sleep 30
 - rspec spec
