neo4j-prod:
  image: neo4j:3.0
  ports:
   - "7474:7474" # http
  volumes:                  
   - ./db-prod/data:/data
   - ./db-prod/logs:/logs

sinatra:
  build: . 
  ports:
    - "4567:80"
  links:
    - neo4j-prod
